package constants

//Culture constants
const CULTURE_MUTATION_RATE = 6
const CULTURE_TOTAL_CHANCE_PUL = 100

//Genom constants
const GENOM_CODE_LENGTH = 36
const GENOM_CODE_BASE_CULTURE_RANGE = 18
const GENOM_CODE_CULTURE_RANGE = 12
const GENOM_CODE_LOCAL_CULTURE_RANGE = 6

//System constants
const SYSTEM_UNLOOP = 10000

//Version constants
const VERSION_PREF = "0.04"
const VERSION_MID = ""
const VERSION_POST = "272"
const VERSION_SMALL = VERSION_PREF + VERSION_MID
const VERSION_FULL = VERSION_SMALL + "." + VERSION_POST
